services:
  # Ollama service for AI model hosting
  ollama:
    image: ollama/ollama:latest
    container_name: kisz-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_entrypoint.sh:/ollama_entrypoint.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    entrypoint: [ "/bin/bash", "/ollama_entrypoint.sh" ]
    healthcheck:
        test: [ "CMD-SHELL", "curl -f http://localhost:11435 || exit 1" ]
        interval: 30s
        timeout: 10s
        retries: 5

  # Backend API service
  backend:
    build:
      context: ./02_backend
      dockerfile: Dockerfile
    container_name: kisz-backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    volumes:
      - ./02_backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend service
  frontend:
    build:
      context: ./01_frontend
      dockerfile: Dockerfile
    container_name: kisz-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./01_frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  ollama_data: