services:
  # Ollama service for AI model hosting
  ollama:
    image: ollama/ollama:latest
    container_name: aisc-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  # Backend API service
  backend:
    build:
      context: ./02_backend
      dockerfile: Dockerfile
    container_name: aisc-backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    volumes:
      - ./02_backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend service
  frontend:
    build:
      context: ./01_frontend
      dockerfile: Dockerfile
    container_name: aisc-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./01_frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  ollama_data: